name: Setup action
description: Setup build action

runs:
  using: "composite"
  steps:
#    - uses: TheMrMilchmann/setup-msvc-dev@v3
#      with:
#        arch: x86
#        sdk: 10.0.26100.0
    - name: Download Visual Studio Installer
      run: |
        Invoke-WebRequest -Uri "https://download.visualstudio.microsoft.com/download/pr/f55fba7b-3f02-49b7-9aca-a075049a807d/156d03c3d97ceb7b5e07f86ae34389af7ee7470fb68059a4a0a0d1ac3bce35b7/vs_BuildTools.exe" -OutFile vs_buildtools.exe
      shell: powershell

    - name: Install Windows SDK 10.0.26100
      run: |
        # The component ID for Windows 11 SDK (10.0.26100.0) is "Microsoft.VisualStudio.Component.Windows11SDK.26100"
        # We use --add to ensure the component is added.
        # --passive makes the installation process silent.
        # --norestart prevents a system restart after installation.
        .\vs_buildtools.exe --quiet --wait --add Microsoft.VisualStudio.Component.Windows11SDK.26100 --passive --norestart
        .\vs_buildtools.exe --quiet --wait --add Microsoft.VisualStudio.Component.DebuggingTools.Windows --passive --norestart
      shell: powershell
    - name: Verify SDK Installation (Optional)
      run: |
        # This step is optional but highly recommended to confirm the SDK is present.
        # It looks for the SDK directory.
        $sdkPath = "C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0"
        if (Test-Path $sdkPath) {
            Write-Host "Windows SDK 10.0.26100 found at $sdkPath"
        } else {
            Write-Error "Windows SDK 10.0.26100 not found at $sdkPath"
            exit 1
        }
      shell: powershell

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Setup depot tools
      uses: 2ndlab/actions/setup-depot-tools@main

    - name: Setup PATH and ENV
      shell: pwsh
      run: |
        echo "ANGLEStaticName=angle-x86-windows-static-chromium-$env:ANGLE_Branch-$env:UCRTVersion" >> $env:GITHUB_ENV
        echo "BuildDir=$env:GITHUB_WORKSPACE/out/windows/x64" >> $env:GITHUB_ENV
